# Header
menu:
  Início: /
  Arquivo: /archives/
  GitHub: https://github.com/jeanonline
  Twitter: https://twitter.com/jeanjoinville
  Rss: /atom.xml

# Content
excerpt_link: Ler mais...
fancybox: true
language: pt

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics: UA-87153494-2
favicon: /favicon.png
twitter: https://twitter.com/jeanjoinville
google_plus: https://plus.google.com/u/0/+JeanCarlosAntonioPereira
fb_admins:
fb_app_id:
